Mi proyecto/gimnasio/app/urls.py
from django.urls import path
from .views import home, contacto, planes, agregar_plan, listar_planes, modificar_plan, eliminar_plan, informacion, iniciar_sesion, registro_usuario

urlpatterns = [
    path('',home, name='home'),
    path('contacto/', contacto, name='contacto'),
    path('planes/', planes, name='planes'),
    path('agregar_plan/', agregar_plan, name='agregar_plan'),
    path('listar_planes/', listar_planes, name='listar_planes'),
    path('modificar_plan/<id>/', modificar_plan, name='modificar_plan'),
    path('eliminar_plan/<id>/', eliminar_plan, name='eliminar_plan'),
    path('informacion/', informacion, name='informacion'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('registro_usuario/', registro_usuario, name='registro_usuario'),
]

Mi proyecto/gimnasio/gimnasio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

Mi proyecto/gimnasio/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class Plan(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nombre

opciones_consultas = [
    [0, "consulta"],
    [1, 'Reclamo'],
    [2, 'Sugerencia'],
    [3, 'Otros'],
]
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField(max_length=50)
    def __str__(self):
        return self.nombre
    
class UsuarioManager(BaseUserManager):
    def create_user(self, email, nombre, password=None, tipo_usuario='cliente'):
        if not email:
            raise ValueError('El email debe ser proporcionado')
        email = self.normalize_email(email)
        user = self.model(email=email, nombre=nombre, tipo_usuario=tipo_usuario)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nombre, password=None):
        user = self.create_user(email, nombre, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    

class Usuario(AbstractBaseUser):
    TIPO_USUARIO_CHOICES = (
        ('cliente', 'Cliente'),
        ('personal', 'Personal del Gimnasio'),
    )

    email = models.EmailField(unique=True)
    nombre = models.CharField(max_length=100)
    tipo_usuario = models.CharField(max_length=10, choices=TIPO_USUARIO_CHOICES, default='cliente')
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nombre']

    objects = UsuarioManager()

    def __str__(self):
        return self.nombre






Mi proyecto/gimnasio/app/forms.py
from django import forms
from .models import Contacto, Plan
from .models import Usuario

class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = '__all__'

class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = '__all__'

class UsuarioRegistroForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Confirmar Contraseña")
    tipo_usuario = forms.ChoiceField(choices=Usuario.TIPO_USUARIO_CHOICES)

    class Meta:
        model = Usuario
        fields = ['email', 'nombre', 'password', 'password2', 'tipo_usuario']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        
        return cleaned_data

Mi proyecto/gimnasio/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Plan
from .forms import ContactoForm, PlanForm
from django.contrib import messages
from .models import Usuario
from .forms import UsuarioRegistroForm
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm


def informacion(request):
    return render(request, 'app/informacion.html')

def home(request):
    return render(request, 'app/home.html')

def contacto(request):
    data = {
        'form': ContactoForm()
    }
    if request.method == 'POST':
        formulario = ContactoForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            data['Mensaje']='Contacto guardado correctamente'
        else:
            data['form'] = formulario

    return render(request, 'app/contacto.html', data)

def planes(request):
    planes = Plan.objects.all()
    data = {
        'planes': planes
    }
    return render(request, 'app/planes.html', data)


def agregar_plan(request):
    data = {
        'form': PlanForm()
        }   
    if request.method == 'POST':
        formulario = PlanForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data['Mensaje']='Plan agregado correctamente'
            return redirect(to='planes')
        else:
            data['form'] = formulario
    return render(request, 'app/planes/agregar.html',data)


def listar_planes(request):
    planes = Plan.objects.all()
    data = {
        'planes': planes
        }
    return render(request, 'app/planes/listar.html', data)


def modificar_plan(request, id):
    plan = get_object_or_404(Plan, pk=id)  
    if request.method == 'POST':
        form = PlanForm(request.POST, instance=plan)
        if form.is_valid():
            form.save()
            messages.success(request, 'Modificado correctamente')
            return redirect(to='listar_planes')
    else:
        form = PlanForm(instance=plan)  
    
    return render(request, 'app/planes/modificar.html', {'form': form})

def eliminar_plan(request,id):
    plan = get_object_or_404(Plan, pk=id)
    plan.delete()
    return redirect(to='listar_planes')

def registro_usuario(request):
    if request.method == 'POST':
        form = UsuarioRegistroForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            nombre = form.cleaned_data['nombre']
            password = form.cleaned_data['password']
            tipo_usuario = form.cleaned_data['tipo_usuario'] 
            usuario = Usuario.objects.create_user(
                email=email, 
                nombre=nombre, 
                password=password, 
                tipo_usuario=tipo_usuario
            )

            login(request, usuario)
            return redirect(to='home')
        else:
            print(form.errors)  
            messages.error(request, "Hubo un problema al registrar el usuario.")
    else:
        form = UsuarioRegistroForm()

    return render(request, 'registration/registro.html', {'form': form})


def iniciar_sesion(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect(to='home')  
        else:
            messages.error(request, "Credenciales incorrectas.")
    else:
        form = AuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})



Mi proyecto/gimnasio/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gimnasio{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/css/styles.css' %}">
</head>
<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">
                        Wolvergym
                    </a>

                    <div class="d-flex justify-content-center w-100">
                        <a href="/">
                            <img src="{% static 'app/imagenes/Logo.png' %}" alt="Logo WolverGym" class="logo-navbar">
                        </a>
                    </div>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item"><a class="nav-link" href="/">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="/planes/">Planes</a></li>
                            <li class="nav-item"><a class="nav-link" href="/contacto/">Contacto</a></li>
                            <li class="nav-item"><a class="nav-link" href="/informacion/">Informacion</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'registro_usuario'%}">Registrarse</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'agregar_plan' %}">Agregar Plan</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'listar_planes' %}">Ver Planes</a></li>
                            {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">@{{user.username}}</a></li>
                            {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'iniciar_sesion' %}">Iniciar Sesión</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div id='contenido'>
        </div>

        <main class="container my-4">
            {% block content %}{% endblock %}
        </main>

        <footer class="bg-danger text-white text-center py-3">
            <p>© 2024 Wolvergym</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    'title': 'Felicitaciones',
                    'text': '{{m}}',
                    'icon': 'success'
                })
            </script>
        {% endfor %}
    {% endif %}

</body>
</html>

Mi proyecto/gimnasio/app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% block title %}Contacto{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center bg-danger text-white">
                    <h4>Contáctanos</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{% url 'contacto' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                            <input type="reset" value='Cancelar' class="btn btn-primary btn-center">
                            <button type="submit" class="btn btn-danger btn-center">Enviar Mensaje</button>
                        </div>
                    </form>
                    {{Mensaje}}
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center bg-danger text-white">
                    <h4>Nuestra Ubicación</h4>
                </div>
                <div class="card-body">
                    <div class="ratio ratio-16x9">
                        
                        <iframe 
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1933.524982970154!2d-71.2532727199273!3d-34.988195761472824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9664571072ae5097%3A0x1d388553ac7ff3e4!2sVaticano%201139%2C%203344106%20Curic%C3%B3%2C%20Maule!5e0!3m2!1ses-419!2scl!4v1732153313543!5m2!1ses-419!2scl" 
                            width="600" 
                            height="450" 
                            style="border:0;" 
                            allowfullscreen="" 
                            loading="lazy"
                            referrerpolicy="no-referrer-when-downgrade">
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Mi proyecto/gimnasio/app/templates/app/home.html
{% extends 'app/base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="display-4">Bienvenido a Wolvergym</h1>
    <p class="lead">Aquí encontraras informacion sobre cual es nuestra mision y nuestra visión.</p>
    <a href="/planes/" class="btn btn-danger btn-lg">Ver Planes</a>
</div>
<section class="mission-vision">
    <div class="container">
        <h2 class="section-title">Misión</h2>
        <p class="mission-vision-content">
            Ser un gimnasio líder en el desarrollo de la fuerza física, mental y espiritual, ofreciendo un entorno seguro, motivador y equipado con la implementación adecuada, para que cada miembro alcance su máximo potencial y supere sus límites personales.
        </p>

        <h2 class="section-title">Visión</h2>
        <p class="mission-vision-content">
            Convertirnos en una referencia regional en el entrenamiento de fuerza, promoviendo una comunidad comprometida con un estilo de vida saludable, resiliente y lleno de energía, donde cada individuo encuentre inspiración y herramientas para transformar su cuerpo, mente y espíritu.
        </p>
    </div>
</section>
{% endblock %}


Mi proyecto/gimnasio/app/templates/app/informacion.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Información del Gimnasio - Wolvergym{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-4">Información del Gimnasio</h1>
    
    
    <section class="mb-5">
        <h2>Historia de Wolvergym</h2>
        <p>Wolvergym comenzó como un pequeño gimnasio en 2010 con la misión de ayudar a las personas a alcanzar sus objetivos de fitness. Hoy en día, somos un gimnasio reconocido con equipos de última generación y un equipo de profesionales altamente capacitados. Nuestro objetivo es brindar un espacio cómodo y motivador para todos nuestros miembros.</p>
    </section>

    
    <section class="mb-5">
        <h2>Conoce al Personal</h2>
        <div class="row">
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% static 'app/imagenes/entrenador1.jpeg' %}" class="card-img-top" alt="Entrenador 1">
                    <div class="card-body">
                        <h5 class="card-title">Ignacio Chamorro</h5>
                        <p class="card-text">Preparador físico, instructor de zumba, strong nation, zumba kids.</p>
                        <p><strong>Redes Sociales:</strong></p>
                        <a href="https://www.instagram.com/ignacio.cl.pf/profilecard/?igsh=MWl6amZubXgxaDQ1NQ==" class="btn btn-danger" target="_blank">Instagram</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="" class="card-img-top" alt="Entrenador 2">
                    <div class="card-body">
                        <h5 class="card-title">Mehiby Soto</h5>
                        <p class="card-text">Nutricionista, especializada en dietas deportivas.</p>
                        <p><strong>Redes Sociales:</strong></p>
                        <a href="https://www.instagram.com/mehiby95/profilecard/" class="btn btn-danger" target="_blank">Instagram</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    
    <section class="mb-5">
        <h2>Ubicación</h2>
        <p>Nos encontramos en la siguiente dirección:</p>
        <address>
            Villa vaticano #1139, Ciudad, Curicó.<br>
            Teléfono: +56 9 7376 8161<br>
            Instagram: Wolvergym
        </address>

        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1933.524982970154!2d-71.2532727199273!3d-34.988195761472824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9664571072ae5097%3A0x1d388553ac7ff3e4!2sVaticano%201139%2C%203344106%20Curic%C3%B3%2C%20Maule!5e0!3m2!1ses-419!2scl!4v1732153313543!5m2!1ses-419!2scl" 
            width="600" 
            height="450" 
            allowfullscreen="" 
            loading="lazy"></iframe>
        </div>
    </section>

    <section class="mb-5">
        <h2>Síguenos en Nuestras Redes Sociales</h2>
        <ul class="list-unstyled d-flex justify-content-center">
            <div class="social-media">
                <a href="https://www.instagram.com/wolvergym22/profilecard/?igsh=MXNkYTIwd3Q5d3A3dQ==" target="_blank">
                    <img src="{% static 'app/imagenes/instagram.png' %}" alt="Instagram" class="social-icon">
                </a>
                <a href="https://www.facebook.com/wolvergym2022?mibextid=ZbWKwL" target="_blank">
                    <img src="{% static 'app/imagenes/facebook.png' %}" alt="Facebook" class="social-icon">
                </a>
                <a href="https://www.tiktok.com/@ignaciopf1?is_from_webapp=1&sender_device=pc" target="_blank">
                    <img src="{% static 'app/imagenes/tiktok.png' %}" alt="Tiktok" class="social-icon">
                </a>
            </div>    
        </ul>
    </section>
</div>
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

Mi proyecto/gimnasio/app/templates/app/planes.html
{% extends 'app/base.html' %}

{% block title %}Planes{% endblock %}

{% block content %}
<h1 class="text-center mb-4">Nuestros Planes</h1>
{% load humanize %}
<div class="row">
    {% for p in planes %}
    <div class="col-12 col-md-6 mb-4">
        <div class="card h-100">
            <div class="card-header bg-danger text-white text-center">
                <h4>{{ p.nombre | capfirst }}</h4>
            </div>
            <div class="card-body">
                <p>{{ p.descripcion | capfirst }}</p>
                <p>${{ p.precio | intcomma }}</p>
            </div>
            <div class="card-footer text-center">
                <a href="#" class="btn btn-danger">Contratar</a>
            </div>
        </div>
    </div>
    {% empty %}
        <p class="text-center">No hay planes disponibles en este momento.</p>
    {% endfor %}
</div>
{% endblock %}


Mi proyecto/gimnasio/app/templates/app/planes/agregar.html
{% extends 'app/base.html'%}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                <h2>Nuevo Plan</h2>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="form-group mb-3">
                        <label for="id_nombre">Nombre</label>
                        {{ form.nombre }}
                    </div>

                    <div class="form-group mb-3">
                        <label for="id_descripcion">Descripción</label>
                        {{ form.descripcion }}
                    </div>

                    <div class="form-group mb-3">
                        <label for="id_precio">Precio</label>
                        {{ form.precio }}
                    </div>

                    
                    <div class="d-flex justify-content-center mt-3">
                        <input type="submit" value="Guardar" class="btn btn-primary">
                        <input type="reset" value="Cancelar" class="btn btn-secondary ms-2">
                    </div>
                </form>

                
                <div class="mt-3">
                    {{ Mensaje }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


Mi proyecto/gimnasio/app/templates/app/planes/listar.html
{% extends 'app/base.html'%}

{% block content %}
<br>
<br>
<br>
<div class='card'>
    <div class='card-body'>
        <h2>Listado de Planes</h2>
        <table class='table table-striped table-hover table-responsive-sm'>
            <tr>

                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Precio</th>
                <th>Acciones</th>

            </tr>
            {% for p in planes%}
            <tr>
                <td>{{p.nombre | title}}</td>
                <td>{{p.descripcion}}</td>
                <td>{{p.precio}}</td>
                <td>
                    <a href="{% url 'modificar_plan' p.id %}" class='btn btn-primary'>Modificar</a>
                    <a href="{% url 'eliminar_plan' p.id %}" class='btn btn-danger'>Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

Mi proyecto/gimnasio/app/templates/app/planes/modificar.html
{% extends 'app/base.html'%}


{% block content %}

        <div class= 'row'>
            <div class = 'col-12 col-md-6 mb-4'>
                <div class = 'card'>
                    <div class = 'card-body' >
                        <h2>Editar Plan</h2>
                        <hr>
                        <form action='' method='post' enctype='multipart/form-data'>

                            {% csrf_token %}
                            {{form}}

                            <div class='d-flex justify-content-center'>
                                <input type='submit' value='Editar' class='btn btn-primary'>
                                <input type='reset' value='Cancelar' class='btn btn-secondary'>
                            </div>
                            
                        </form>
                        {{Mensaje}}
                    </div>
                </div>
            </div>
        </div>

        
    


{% endblock %}